# Generated by Django 2.1 on 2018-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField()),
                ('nomeDono', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='static/restaurante/fotosRestaurante/')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
