# Generated by Django 2.1 on 2018-10-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('nomeDono', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='static/restaurante/fotosRestaurante/')),
                ('email', models.CharField(max_length=50)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Usuario')),
            ],
        ),
    ]
