# Generated by Django 2.1 on 2018-10-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
