# Generated by Django 2.1 on 2018-10-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('comanda', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comanda.Comanda')),
                ('mesa', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comanda.Mesa')),
                ('tipoUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.TipoConta')),
            ],
        ),
    ]
