# Generated by Django 2.1 on 2018-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comanda',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mesa',
            field=models.IntegerField(default=-1),
        ),
    ]
